### ISSUE TITLE
Color Footer

### ISSUE THREAD

**Issue by Bimamaarschal** [Kampus-Merdeka-Software-Engineering/front-end-capstone-project-section-semarang-group-10#3]
Warna footer  masih hitam

**Comment by Fajarns15** [comment]
> Warna footer masih hitam

diganti warna apa kak bim, soalnya aku cari referensi kebanyakan footernya hitam

**Comment by Bimamaarschal** [comment]
warna coba menyesuaikan tema saja kak. agar terlihat sinkron, seperti kuning muda berdasar hexa primary.
